
base_url = "https://hustedt-praxis.de"

title = "Cynthia Hustedt"

description = "Psychologin. Coach. Supervisorin."

build_search_index = false
compile_sass = true
generate_feed = false

[markdown]
external_links_target_blank = true
highlight_code = false

[extra]
navigation = [
  {type = "section", path = "_index.md"},
  {type = "page", path = "ansatz.md"},
  {type = "section", path = "angebote/_index.md"},
  {type = "page", path = "kontakt.md"},
]

footer = [
  {type = "page", path = "impressum.md"},
]
