
base_url = "https://hustedt-praxis.de"

title = "Cynthia Hustedt"

description = "Psychologin. Coach. Supervisorin."

build_search_index = false
compile_sass = true
generate_feed = false

[markdown]
external_links_target_blank = true
highlight_code = false

[extra]
navigation = [
  {type = "page", path = "ueber-mich.md"},
  {type = "section", path = "angebote/_index.md"},
  {type = "page", path = "kontakt.md"},
]

sub_navigation = [
  {type = "page", path = "angebote/psychotherapie.md"},
  {type = "page", path = "angebote/supervision.md"},
  {type = "page", path = "angebote/coaching.md"},
  {type = "page", path = "angebote/paedagogische-beratung.md"},
]

footer = [
  {type = "page", path = "impressum.md"},
]
